### ISSUE TITLE
Feature-Request: ignore magento files for developing

### ISSUE THREAD

**Issue by dermatz** [OpenForgeProject/mageforge#17]
add ./magento/ to .gitignore

**Comment by Morgy93** [comment]
The .gitignore with that entry is already present in the develop branch:

https://github.com/dermatz/mageforge/blob/develop/.gitignore

**Comment by dermatz** [comment]
Yes, but if you switch back to main, the Magento folder still exists.

**Comment by Morgy93** [comment]
The `main` and `develop` branch don't belong together.
The `develop` is for the development environment which has `main` in it.
`main` is the module only.

Just a workaround to have everything in the same repo.
We could also just split it up into two repos.
